application: myapp
version: 1
runtime: go
api_version: go1
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: client/app/css
- url: /img
  static_dir: client/app/img
- url: /js
  static_dir: client/app/js
- url: /bower_components
  static_dir: client/app/bower_components
- url: /views
  static_dir: client/app/views
- url: /dist
  static_dir: client/app/dist
- url: /.*
  script: _go_app
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/grunt/.*
- ^(.*/)?.*/test/.*
- ^(.*/)?.*\.map
- ^(.*/)?.*\.json
